- setup.py
This pull request fix package name in the file: setup.py
> Change package name in the: setup.py

- SNIFFER.md
- sniffer.py
Update the sniffer.py to include the crc fix from TI
> Fix crc issue on TI ncp sniffer

- README.md
- spinel-cli.py
- spinel/codec.py
- spinel/const.py
@jwhui , required by https://github.com/openthread/openthread/pull/1967
> [spinel-cli] replace whitelist to filter-addr along with OT core

- SNIFFER.md
- sniffer.py
It should notify user if it failed to initialize the sniffer.
> [sniffer] output the status after sniffer initialization

- sniffer.py
* Use host side timestamp if NCP sniffer doesn't provide it
* Don't initialize Panid
* Don't check PHY_ENABLED setting result (will still be verified when setting RAW_STREAM_ENABLED)
> [sniffer] backward compatible with the old NCP firmware

- spinel/codec.py
This pull request fixes problem with high CPU load.
> Fix issue #24. Busy loop in queue_wait_for_prop consuming 100% CPU.

- spinel-cli.py
Thread cert tests requires sending packets of different sizes.
* enabled ping with given size of ping payload
* trick: encoded timestamp into identifier and sequence number
> Support ping with given size of payload

- spinel-cli.py
- spinel/stream.py
* add notification to simulator to indicate there's no more UART data for the current command
* avoid zombie process
> [spinel-cli] enhance for virtual time

- .travis.yml
- spinel-cli.py
- spinel/codec.py
- spinel/hdlc.py
- spinel/stream.py
- spinel/util.py
> [python] add support for python3

- spinel/hdlc.py
> [hdlc] return None when FCS does not pass

- spinel/codec.py
Should fix #48 
I'm not sure what was the problem. I cannot reproduce it anymore.
> Fix child table encoding introduced in 408945e

- requirements.txt
> [python] add requirements

- spinel/codec.py
Handle SLAAC addresses inside of OpenThread, required by openthread/openthread#3484
> [slaac] handle on-mesh prefix in OpenThread

- sniffer.py
- spinel/codec.py
This PR adds support for frames with 64bit timestamp.
> [sniffer] support 64bit timestamp

- .travis.yml
- SNIFFER.md
- requirements.txt
- setup.py
- sniffer.py
- spinel-cli.py
- spinel/codec.py
- spinel/common.py
- spinel/hdlc.py
- spinel/ipv6.py
- spinel/stream.py
- spinel/test_codec.py
- spinel/test_stream.py
- spinel/tun.py
- spinel/util.py
The project tried to support python2 and python3, but resulted in both
support are buggy. Since python2 will be ended in Jan, 2020, this PR
removes python2 support from this project.
> [style] remove support for python2

- README.md
- SNIFFER.md
- sniffer.py
- spinel/pcap.py
Sniffer could not work properly since removing python2 support in #73.
>  [sniffer] quick fix for python3 support

- spinel-cli.py
MAC/MLE counters can be cleared with commands:
> counters mac reset
> counters mle reset
> [spinel-cli] counters mac/mle reset

- spinel-cli.py
commit adds support for changing PROP_PHY_CCA_THRESHOLD by pyspinel command:
"mac ccathreshold"
> [spinel-cli] add "mac" command for changing CCA ED Threshold

- spinel-cli.py
Align with regular CLI example.
> [spinel-cli] add txpower command

- README.md
- spinel-cli.py
- vendor/vendor.py
.. and additionally small clean-up.
> [doc] add description about baudrate and debug switches

- .travis/script.sh
- spinel-cli.py
Adds support to:
```
panid 0xface
```
> [spinel-cli] support hex panid

- setup.py
Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>
> [setup.py] conditional ipaddress dep for compatibility with python >= 3.3

- sniffer.py
The packet will be longer than `2 + length + 19`
> [sniffer] support RCP with ACK metadata

- spinel-cli.py
- spinel/codec.py
- spinel/const.py
To promote inclusivity and eliminate any unintentional bias.
> [mac-filter] change whitelist/blacklist to allowlist/denylist

- spinel-cli.py
Required by https://github.com/openthread/openthread/pull/5601.
> [spinel-cli] fix extaddr command

- setup.py
@jwhui Could you please add git tag after this is merged? I will try to upload a new package to pypi.
> [pypi] bump version to 1.0.2

- spinel/codec.py
- spinel/const.py
Required by <https://github.com/openthread/openthread/pull/6645>.
> [codec] add source match properties
