openthread/pyspinel

- setup.py
- spinel-cli.py
- spinel/common.py
- spinel/ipv6.py
This pull request removes ScaPy dependency which causes problems on the Windows OS. PySpinel without ScaPy works properly with python 2.7.
> Remove ScaPy dependency.

- spinel-cli.py
It helps to fix the `ncp-sim` travis check failures on OT master, the test scripts mistook the previous ICMP request message as the expected ICMP reply message: https://travis-ci.org/openthread/openthread/jobs/233462783#L1667
> Only parse and print ICMP reply messages

- .travis.yml
- .travis/script.sh
This PR enables travis CI to for this repo to resolve #8 .
The main purpose is to make sure changes in this repo will not break CI of OpenThread. So this PR simply runs the target `posix-ncp` of OpenThread's CI tests.
> Enable travis ci

- spinel-cli.py
This PR fixes the issue that typing `b` on macOS has no effect.
> allow typing b on macOS

- SNIFFER.md
- sniffer.py
Not only TI's chip don't transmit CRC, some other platforms also don't, for example: nRF52840.
> [sniffer] rename "--ti-crc" to "--crc"

- spinel-cli.py
- spinel/codec.py
The `STREAM_NET` (secure or insecure) can contain an optional metadata
portion after the message payload. This commit ensures these properties
are parsed/unpacked correctly when the metadata is present.
> [codec] Fix the parsing of `STREAM_NET` and `STREAM_NET_INSECURE` spinel properties

- sniffer.py
- spinel/pcap.py
OT sniffer could provide precise timestamp with PR: https://github.com/openthread/openthread/pull/1971.
> [sniffer] use the timestamp from sniffer device

- spinel/codec.py
This change removes the hard-coded length value and replaces it with the `struct_len` derived from the spinel frame.
This should address the failing tests from https://github.com/openthread/openthread/pull/2073
> [codec] ensure to use the struct len when iterating/parsing through list of on-mesh-prefixes

- SNIFFER.md
- sniffer.py
- spinel/stream.py
Some backgrounds:
- The 802.15.4 PHY throughput used by Thread is 250kbps;
- Most of existing OT platforms uart baud rate is 115200;
- Current ncp_uart doesn't support buffer mechanism (single UartTxBuffer).
If there are two packets come from Thread network with very short interval, the second packet may be lost since the previous one is still in the UartTxBuffer sending from NCP to host.
The issue becomes more serious for OT Sniffer when sniffing heavy traffic.
Similar description in [draft-rquattle-spinel-unified.txt](https://github.com/openthread/openthread/blob/master/doc/draft-rquattle-spinel-unified.txt#L3768.)
> [sniffer] add set uart baud rate option

- sniffer.py
It makes the initialization process more stable.
> [sniffer] wait a bit after reset command

- spinel-cli.py
The `NET_STACK_UP` expects a `boolean` value which should be encoded
as 0x00 (for `false`)  and 0x01 (for `true`) per Spinel specification
This commit fixes an issue where value `2` was used for `true`
incorrectly for the `NET_STACK_UP` set operation.
> Fix incorrect NET_STACK_UP set value

- SNIFFER.md
- sniffer.py
This PR adds new --no_reset flag to the spinner.py CLI.
Resetting the NCP with native USB conenction causes it to reenumerate and, as result, not start properly.
In that case adding the mentioned flag makes the sniffer fully funcional.
Signed-off-by: Piotr Szkotak piotr.szkotak@nordicsemi.no
> Add no-reset cli parameter to the sniffer.py to skip NCP reset on init

- SNIFFER.md
- sniffer.py
On Windows, redirecting sniffer output to a file doesn't work
properly due to new line characters processing. This commit
adds a separate option which allows for storing capture to
a file.
Signed-off-by: Wojciech Bober <wojciech.bober@nordicsemi.no>
> Added support for storing capture in a file

- .travis/script.sh
- spinel/stream.py
* close node elegantly to recover code coverage.
* use virtual time to accelerate running tests.
> [spinel-cli] close simulated node elegantly

- setup.py
This PR bumps version of the pyspinel.
Could you please add a new tag `1.0.0a3` to the current master? If possible, could you also replace `wbober` with `LuDuda` in the maintainer list on [pypi](https://pypi.org/project/pyspinel), so i can update version there as well?
> [pypi] bump version to 1.0.0a3

- spinel/codec.py
spinel-cli crashes when asking the version on a KW41Z-NCP node
```
spinel-cli > version
File "/aprojects/rem-nxp/raspberry_pi/pyspinel-1.0.0a3/spinel/codec.py", line 950, in parse_rx
handler(self, payload, tid)
File "/aprojects/rem-nxp/raspberry_pi/pyspinel-1.0.0a3/spinel/codec.py", line 757, in PROP_VALUE_IS
self.handle_prop(wpan_api, "IS", payload, tid)
File "/aprojects/rem-nxp/raspberry_pi/pyspinel-1.0.0a3/spinel/codec.py", line 721, in handle_prop
prop_value = handler(wpan_api, payload[prop_len:])
File "/aprojects/rem-nxp/raspberry_pi/pyspinel-1.0.0a3/spinel/codec.py", line 406, in NCP_VERSION
def NCP_VERSION(self, _, payload): return self.parse_U(payload)
File "/aprojects/rem-nxp/raspberry_pi/pyspinel-1.0.0a3/spinel/codec.py", line 124, in parse_U …
```
> Fix payload nullchar crash

- SNIFFER.md
- sniffer.py
- spinel/pcap.py
The **--tap** flag is used to specify DLTs as [IEEE802_15_4_TAP](https://github.com/jkcko/ieee802.15.4-tap).
The existing DLTs for IEEE 802.15.4 have versions for FCS, NOFCS, NONASK_PHY, and LINUX (address fields padded). The NONASK_PHY includes only fixed preamble bytes, and the FCS/NOFCS versions support for heuristic match for ZBOSS generated format again with some fixed fields.  The proposed format attempts to wrap up the different types into one and provide an extensible TLV format for capture devices to provide additional meta-data.
When capturing from multiple interfaces on different channels by Wireshark, users can see which channel each packet comes from.
> [sniffer] add '--tap' option

- spinel/util.py
If the debug mode was entered using the `debug 1` command, sending any diag command would fail due to encoding error.
> [spinel-cli] fix invalid encoding in debug mode hexify

- spinel-cli.py
- spinel/codec.py
- spinel/config.py
- spinel/hdlc.py
- spinel/stream.py
- spinel/tun.py
I've noticed that currently, **pyspinel** does not work with a debug level higher than 0.
This was partially fixed by #72 but then #73 reintroduce the problem.
**Problem nr 1** Casting
For example if you run the pyspinel with the highest verbosity:
```
ludu@ludu:~/git/pyspinel$ sudo python3 spinel-cli.py -u /dev/ttyACM0 -d 5
DEBUG_ENABLE = 5
Opening serial to /dev/ttyACM0 @ 115200
PROP_VALUE_SET [tid=1]: IPv6_ICMP_PING_OFFLOAD
File "spinel-cli.py", line 2287, in <module>
main()
File "spinel-cli.py", line 2276, in main
shell = SpinelCliCmd(stream, nodeid=options.nodeid)
File "spinel-cli.py", line 190, in __init__
self.prop_set_value(SPINEL.PROP_IPv6_ICMP_PING_OFFLOAD, 1)
File "spinel-cli.py", line 330, in prop_set_value
return …
```
> [logging] fix python issues with logging and use proper logger

- spinel-cli.py
This PR fixes the following error:
```
spinel-cli > bufferinfo
File "spinel-cli.py", line 2347, in <module>
main()
File "spinel-cli.py", line 2339, in main
shell.cmdloop()
File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
return func(arg)
File "spinel-cli.py", line 559, in do_bufferinfo
print("total: %d" % result[0])
TypeError: 'int' object is not subscriptable
```
> [spinel-cli] fix problem with bufferinfo command

- spinel-cli.py
- spinel/codec.py
- spinel/const.py
This PR implements support for `counters` command.
Output is the same as with regular CLI application:
```
spinel-cli > counters mac
TxTotal: 7
TxUnicast: 0
TxBroadcast: 7
TxAckRequested: 0
TxAcked: 0
TxNoAckRequested: 7
TxData: 7
TxDataPoll: 0
TxBeacon: 0
TxBeaconRequest: 0
TxOther: 0
TxRetry: 0
TxErrCca: 0
TxErrBusyChannel: 0
RxTotal: 0
RxUnicast: 0
RxBroadcast: 0
RxData: 0
RxDataPoll: 0
RxBeacon: 0
RxBeaconRequest: 0
RxOther: 0
RxAddressFiltered: 0
RxDestAddrFiltered: 0
RxDuplicated: 0
RxErrNoFrame: 0
RxErrNoUnknownNeighbor: 0
RxErrInvalidSrcAddr: 0
RxErrSec: 0
RxErrFcs: 0
RxErrOther: 0
Done
spinel-cli > counters mle
Role Disabled: 0
Role Detached: 1
Role Child: 0
Role Router: 0
Role Leader: 1
Attach Attempts: 1
Partition Id Changes: 1
Better Partition Attach Attempts: 0
Parent …
```
> [spinel-cli] implement counters command

- README.md
- spinel-cli.py
- spinel/codec.py
- vendor/codec.py
- vendor/const.py
- vendor/vendor.py
Create new vendor module to maintain and use unique Vendor Spinel commnads.
Changes in code don't affect for users without vendor module.
vendor/vendor.py -> definition of unique vendor commands
vendor/const.py -> definition of vendor property constants
vendor/codec.pt -> definition of Spinel Handler and addition of mapping SPINEL_PROP_DISPATCH : WPAN_PROP_HANDLER
> [spinel-cli] extend spinel cli with vendor hooks module

- extcap_ot.bat
- extcap_ot.py
- setup.py
- sniffer.py
- spinel/codec.py
- spinel/hdlc.py
- spinel/pcap.py
- spinel/stream.py
This PR provides a more user-friendly way to use OpenThread Sniffer, refer to the [example](https://github.com/wireshark/wireshark/blob/master/doc/extcap_example.py) provided by Wireshark.
You can see the effect in the draft of the [user guide](https://docs.google.com/document/d/1cyKamVzE41RQZuFvZHJJenm1VCMthl7CnB-FmZFAiyI/edit?usp=sharing).
> [sniffer] better integrate with Wireshark

- EXTCAP.md
- README.md
- SNIFFER.md
- Added links to the openthread.io guides
- Updated some instructions to match the revised guides
- Reformatted some sections for consistency
- Double-checked the output for some spinel-cli commands
> [docs] sync Pyspinel docs with openthread.io guides

- spinel-cli.py
- Fixed bug with setting of 'macfilter rss *' - changed string to byte array to avoid concatenate error:
```spinel-cli > macfilter rss add * 1
File "/home/kasz/repos/kng-verification/.venv/py3/bin/spinel-cli.py", line 2924, in <module>
main()
File "/home/kasz/repos/kng-verification/.venv/py3/bin/spinel-cli.py", line 2915, in main
shell.cmdloop()
File "/usr/local/lib/python3.7/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/usr/local/lib/python3.7/cmd.py", line 217, in onecmd
return func(arg)
File "/home/kasz/repos/kng-verification/.venv/py3/bin/spinel-cli.py", line 2583, in do_macfilter
arr += struct.pack('b', rssi)
TypeError: can only concatenate str (not "bytes") to str
```
- Fixed bug with clearing rules of macfilter rss and addr
- Some …
> [spinel-cli] fix bug with macfilter command

- .travis/script.sh
v0.30.0 (released on 2020-04-23) introduces formatting changes that
are not compatible with v0.29.0.
> [pretty] fix yapf version to 0.29.0

- README.md
- spinel-cli.py
- spinel/codec.py
Introduce a `--vendor-path` option which allows to provide a custom location of the vendor package. It is also possible to provide this location with `SPINEL_VENDOR_PATH` environmental variable.
> [spinel-cli] add vendor path option

- setup.py
@jwhui Seems it was very bad idea to create a package for pypi on Windows.. since line-endings are not correctly interpreted on Linux now.
I'm sorry for this issue and your additional effort but i need to upload a new version to pypi - this time from Linux and correct line-endings. Already verified locally. Pypi does not allow to replace the package, so we need to bumb the version again.
> [pypi] bump version to 1.0.3

- spinel/codec.py
It fixes the exception:
```
python3 spinel-cli.py -u /dev/ttyACM1 -d 3
DEBUG_ENABLE = 3
PROP_VALUE_SET [tid=1]: IPv6_ICMP_PING_OFFLOAD
TX Pay: (4) 81036501 
RX Pay: (21) 8006704672616d696e67206572726f7220363a205b 
PROP_VALUE_IS [tid=0]: STREAM_DEBUG = b'Framing error 6: ['
File "/home/luma/workspace/pyspinel/spinel/codec.py", line 1110, in parse_rx
handler(self, payload, tid)
File "/home/luma/workspace/pyspinel/spinel/codec.py", line 808, in PROP_VALUE_IS
self.handle_prop(wpan_api, "IS", payload, tid)
File "/home/luma/workspace/pyspinel/spinel/codec.py", line 797, in handle_prop
CONFIG.LOGGER.debug("DEBUG: " + prop_value)
TypeError: can only concatenate str (not "bytes") to str
```
> [codec] fix property value concatenation in debug message

- spinel/codec.py
As said in https://github.com/openthread/pyspinel/issues/113, pyspinel failed to parse STREAM_LOG. 
This is because the format of STREAM_LOG is "UD" but pyspinel has no idea where the utf-8 part ends. Therefore it tries to decode the whole data as utf-8 then it fails when there's an invalid utf-8 character. In this PR I made pyspinel decode utf-8 as far as it can until it meets an invalid character.
> [codec] handle failures when decoding utf-8

- spinel-cli.py
For certain Windows installs, readline.doc is None. Check before trying to search for the phrase "libedit" inside it.
> [spinel-cli] add handling for Windows readline.__doc__ is NoneType error

- spinel/pcap.py
fix FCS format error. In the TI style FCS, the first byte is RSSI and the last byte is LQI.
related : [sniffer] quick fix for python3 support [#76](https://github.com/openthread/pyspinel/pull/76)
> [pcap] fix FCS format error

- .github/ISSUE_TEMPLATE.md
- setup.py
Replace link to openthread-users Google Group with link to GitHub OpenThread Discussions, clarify issue reporting links.
> [docs] community discussion change

- spinel/codec.py
Adding a fix for #124 by unpacking the various types of responses that come back from the MAC_ALLOWLIST property. Note that there are three different formats, so we try them from the most complex/involved to the least complex/involved.
1. Try to decode an array of structures composed of an EUI64 and an unsigned 8-bit integer (from querying the value)
2. If that fails, try to decode a single entry composed of an EUI64 and an unsigned 8-bit integer (from inserting a value)
3. If that fails, try to decode a single entry composed of only an EUI64 (from deleting an entry)
4. If all of these fail, return None
> [codec] add decoding for allowlists that are passed back from the NCP
